In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from Neural_net import NeuralNet


In [3]:
iris = pd.read_csv("./Iris.csv")

In [4]:
iris = iris.sample(frac=1).reset_index(drop=True)

In [5]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [6]:
X = iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']]
X = np.array(X)

In [7]:
y = iris.Species

In [8]:
encoder =  OneHotEncoder(sparse=False)
y = encoder.fit_transform(np.array(y).reshape(-1,1))

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.15)
X_train,X_val,y_train,y_val = train_test_split(X,y,test_size=0.15)

In [13]:
nn=NeuralNet()

In [14]:

#w=InitializeWeights([3,4,3])

In [15]:
weights = nn.InitializeWeights([3,3,4,5])

Theta1 1 is (3, 4)
Theta1 2 is (4, 4)
Theta1 3 is (5, 5)


In [16]:
weights

[array([[-0.76463252,  0.6909323 , -0.10876818, -0.82299137],
        [ 0.71320395,  0.12486164,  0.9482192 , -0.86996608],
        [-0.39961706, -0.97976646, -0.662061  ,  0.04012776]]),
 array([[-0.53806541,  0.58582762, -0.9121192 , -0.1150102 ],
        [-0.14231397, -0.29630867,  0.94849173, -0.81622017],
        [-0.69787778,  0.33114079,  0.7961069 , -0.4841793 ],
        [-0.36246622, -0.33001124,  0.19654102, -0.60430856]]),
 array([[ 0.59909059,  0.69609306,  0.86170596,  0.10561817,  0.29161393],
        [ 0.86651222,  0.68587226, -0.82000978,  0.87915264,  0.33580108],
        [ 0.14567261,  0.91552257,  0.65350262,  0.81406803, -0.30666841],
        [ 0.82989681,  0.9105989 , -0.08926163,  0.52756848, -0.79915448],
        [-0.95523877, -0.4091917 , -0.57741725,  0.75514184,  0.70298474]])]

In [65]:
InitializeWeights2([2,4,5,6])

[matrix([[ 0.18734793, -0.37829884,  0.67842295],
         [-0.27675087, -0.73787918,  0.36448819],
         [-0.5488351 ,  0.27004328,  0.83267217],
         [ 0.11737324, -0.91762755, -0.4757651 ]]),
 matrix([[ 0.04785949, -0.0395794 , -0.16293938,  0.75851122,  0.91265147],
         [-0.83596415,  0.93492189, -0.31229461, -0.59771368, -0.92454887],
         [-0.02916072, -0.79277271,  0.5740178 , -0.41649812,  0.20260036],
         [-0.01923846, -0.59580988,  0.55597281, -0.08039979,  0.09142973],
         [ 0.67276713, -0.47144907, -0.02109657, -0.54717868,  0.7665476 ]]),
 matrix([[-0.9123643 , -0.18977416,  0.73377923,  0.00263393,  0.12677134,
           0.92227805],
         [ 0.14624842, -0.75030769,  0.57119202, -0.14278296, -0.94445887,
           0.01616189],
         [ 0.58246066,  0.41517008, -0.0032809 ,  0.93138032,  0.71193962,
          -0.33424083],
         [-0.72852519, -0.42685655,  0.23539893, -0.62672142, -0.91067709,
           0.70702944],
         [-0.3773316