In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
#from Neural_net import NeuralNet


In [2]:
iris = pd.read_csv("./Iris.csv")

In [3]:
iris = iris.sample(frac=1).reset_index(drop=True)

In [4]:
iris.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [5]:
X = iris[['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']] 
X = np.array(X)

In [6]:
y = iris.Species

In [7]:
encoder =  OneHotEncoder(sparse=False)
y = encoder.fit_transform(np.array(y).reshape(-1,1))

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.15)
X_train,X_val,y_train,y_val = train_test_split(X,y,test_size=0.1)

In [9]:
'''' class NeuralNet():
    def __init__(self,X,y,layers):
        self.X=X
        self.y=y
        self.layers = layers
        self.nofl = len(self.layers)
        self.weights = self.InitializeWeights()
        self.X_train,self.X_test,self.y_train,self.y_test = train_test_split(X,y,test_size=0.15)
        self.X_train,self.X_val,self.y_train,self.y_val = train_test_split(X,y,test_size=0.1)


    def printall(self):
        '''test function to test import '''
        print("NN class")

    def InitializeWeights(self):
        ''' Initailises the theta matrix with random valuse'''
        self.weights = []
        #self.layers = layers
        #slef.nofl = len(self.layers)
        for i in range(1,self.nofl):
            w = np.array([[np.random.uniform(-1,1) for k in range(self.layers[i-1]+1)] for j in range(self.layers[i])])
            print('Theta1 {} is {}'.format(i,w.shape))
            self.weights.append(w)
        return self.weights
    
    def sigmoid(self,z):
        z=1.0/(1.0+np.exp(-z))
        return z
    
    def sigmoidDerivative(self,x):
        return x*(1-x) '''

In [9]:

def InitializeWeights(layers):
    ''' Initailises the theta matrix with random valuse'''
    weights = []
    #self.layers = layers
    nofl = len(layers)
    for i in range(1,nofl):
        w = np.array([[np.random.uniform(-1,1) for k in range(layers[i-1]+1)] for j in range(layers[i])])
        print('Theta1 {} is {}'.format(i,w.shape))
        weights.append(w)
    return weights

In [18]:
nn=NeuralNet(X,y,[4,2,3])

Theta1 1 is (2, 5)
Theta1 2 is (3, 3)


In [11]:
#weights=[]
#weights = nn.InitializeWeights([4,2,6,4])
randw=InitializeWeights([4,5,5,3])

Theta1 1 is (5, 5)
Theta1 2 is (5, 6)
Theta1 3 is (3, 6)


In [12]:
def sigmoid(z):
    z=1.0/(1.0+np.exp(-z))
    return z
    

In [13]:
#weights = nn.weights
#weights = InitializeWeights([4,5,5,3])

In [16]:
randw

[array([[ 0.94309749,  0.73826401, -0.05682383, -0.72888055,  0.2770309 ],
        [ 0.78864343, -0.78180003,  0.20731104,  0.07772142,  0.25141022],
        [ 0.09339987, -0.17838092, -0.02497659,  0.34702986,  0.72957425],
        [ 0.15316139,  0.17988131,  0.49414663,  0.19916019,  0.27723683],
        [ 0.46304925,  0.56060196,  0.90451938,  0.7281644 , -0.7581826 ]]),
 array([[ 0.84495818, -0.40811993, -0.66367367, -0.59712342, -0.48188517,
         -0.99817736],
        [ 0.58659139,  0.47216348,  0.91426635, -0.96548728, -0.24374005,
         -0.58290351],
        [-0.84539859,  0.27376664, -0.37281541, -0.66650659,  0.34367876,
          0.07346123],
        [-0.18025093, -0.27510989, -0.49215376,  0.37987578,  0.38929579,
         -0.47891937],
        [ 0.88142958, -0.80883323,  0.00188232, -0.34525714, -0.49587568,
         -0.62284154]]),
 array([[ 0.11004747, -0.96157386,  0.33494735, -0.9660967 ,  0.5050076 ,
          0.97755188],
        [-0.64267286, -0.0784021 , -0.8

In [17]:
def forwardPropagation(x,weights):
    numofl=len(weights)+1
    activation = [x]
    nodes=np.ones((x.shape[0],x.shape[1]+1))
    nodes[:,1:]=x
    #print(nodes.shape)
    for i in range(numofl-1):
        a = sigmoid(nodes.dot(weights[i].T))
        activation.append(a)
        nodes=np.ones((a.shape[0],a.shape[1]+1))
        nodes[:,1:]=a
       # print("Foreward propagating theta {}".format(i+1))
    #print(activation.shape)
    return activation
        
        

In [18]:
a = forwardPropagation(X_train,randw)


In [19]:
def sigmoidDerivative(x):
    return x*(1-x)

In [20]:
def backPropagation(y,activation,weights,lr=0.15):
    nofl=len(weights)+1
    output = activation[-1]
    error = y-output
    for j in range(nofl-1,0,-1):
        curact=activation[j]
        nodes=np.ones((activation[j-1].shape[0],activation[j-1].shape[1]+1))
        nodes[:,1:]=activation[j-1]
        preact= nodes
        
        
        print(curact.shape,error.shape)
        delta = error*sigmoidDerivative(curact)
        weights[j-1] += lr*(delta.T.dot(preact))
        print(delta.shape,preact.shape)
        error = delta.dot(weights[j-1][:,1:])
        print(error.shape)
    return weights

In [18]:
trainedweights = backPropagation(y_train,a,weights,0.15)

(135, 3) (135, 3)
(135, 3) (135, 5)
(135, 4)
(135, 4) (135, 4)
(135, 4) (135, 6)
(135, 5)
(135, 5) (135, 5)
(135, 5) (135, 3)
(135, 2)
(135, 2) (135, 2)
(135, 2) (135, 5)
(135, 4)


In [21]:
def train(X,y,weights,lr=0.15):
    nofl=len(weights)+1
    activations = forwardPropagation(X,weights)
    weights = backPropagation(y,activations,weights,lr)
    return weights
    
    

In [22]:
reweights = train(X_train,y_train,randw)

(135, 3) (135, 3)
(135, 3) (135, 6)
(135, 5)
(135, 5) (135, 5)
(135, 5) (135, 6)
(135, 5)
(135, 5) (135, 5)
(135, 5) (135, 5)
(135, 4)


In [23]:
def predict(x,weights):
    nofl=len(weights)+1
    activation = forwardPropagation(x,weights)
    output = activation[-1]
    
    return output
    
    
    

In [24]:
reweights
predict(X_test,reweights)

array([[0.11684721, 0.2046067 , 0.09509725],
       [0.11371976, 0.2037693 , 0.09453039],
       [0.11380627, 0.20495355, 0.09341017],
       [0.11252873, 0.20455317, 0.09353264],
       [0.11260851, 0.20398146, 0.0939885 ],
       [0.11341741, 0.2034929 , 0.0944082 ],
       [0.11182814, 0.20378661, 0.09323349],
       [0.11506852, 0.20517069, 0.09419304],
       [0.1134672 , 0.2037874 , 0.09438738],
       [0.11532435, 0.20472143, 0.09426544],
       [0.11335408, 0.20457791, 0.09336124],
       [0.1132128 , 0.20408432, 0.0932756 ],
       [0.11484849, 0.20538003, 0.09445977],
       [0.1118064 , 0.20355307, 0.0931501 ],
       [0.1134364 , 0.20362453, 0.09397513],
       [0.11414796, 0.20390029, 0.09433764],
       [0.11352342, 0.20481419, 0.09342871],
       [0.11190648, 0.20355317, 0.09316696],
       [0.11268285, 0.20418243, 0.09327554],
       [0.1126849 , 0.20465708, 0.09348947],
       [0.11325189, 0.20376073, 0.09412478],
       [0.11415698, 0.20464672, 0.09432517],
       [0.

In [25]:
#X_test.shap
randw

[array([[ 0.96558471,  0.87057233,  0.00932784, -0.63643659,  0.30685465],
        [ 0.79929442, -0.75668901,  0.25338315,  0.01461573,  0.21936015],
        [ 0.04506636, -0.45071557, -0.16794395,  0.18388178,  0.68206429],
        [ 0.15974833,  0.2160252 ,  0.51405114,  0.21939293,  0.28313995],
        [ 0.46291482,  0.55994012,  0.90410544,  0.72792972, -0.75822696]]),
 array([[ 1.00042283, -0.2767671 , -0.65792504, -0.40548123, -0.32521651,
         -0.84265217],
        [ 0.89132304,  0.77283368,  0.94649726, -0.85605306,  0.04494356,
         -0.27846941],
        [-0.61586105,  0.46825175, -0.36398763, -0.38938535,  0.57487105,
          0.30307965],
        [ 0.03330282, -0.062911  , -0.4688312 ,  0.44724612,  0.59097726,
         -0.26558845],
        [ 0.79314285, -0.88378276, -0.00172023, -0.44881872, -0.58477567,
         -0.71115505]]),
 array([[-0.98331155, -1.12879166,  0.02375601, -1.26438918, -0.01428047,
          0.74863872],
        [-0.15667227,  0.00515687, -0.6

In [26]:
#forwardPropagation(X_train, weights)

In [107]:
def BackPropagation(y, activations, weights,lr):
    outputFinal = activations[-1]
    layers = len(weights)+1
    error = np.matrix(y - outputFinal) # Error at output
    print(layers)
    
    
    for j in range(layers-1, 0, -1):
        currActivation = activations[j]
        print(currActivation.shape)
        nodes=np.ones((activations[j-1].shape[0],activations[j-1].shape[1]+1))
        nodes[:,1:]=activations[j-1]
        prevActivation= nodes
        ''' 
       if(j > 1):
            # Augment previous activation
            prevActivation = np.append(1, activations[j-1])
        else:
            # First hidden layer, prevActivation is input (without bias)
            prevActivation = activations[0] '''
       #print(prevActivation)
        delta = np.multiply(error, sigmoidDerivative(currActivation))
        weights[j-1] += lr * np.dot(delta.T, prevActivation)
        print("{} done".format(j))

        w = np.delete(weights[j-1], [0], axis=1) # Remove bias from weights
        error = np.dot(delta, w) # Calculate error for current layer
    
    return weights

In [108]:
randw= InitializeWeights([4,5,5,3])
a= forwardPropagation(X_train,randw)

Theta1 1 is (5, 5)
Theta1 2 is (5, 6)
Theta1 3 is (3, 6)


In [109]:
bp = BackPropagation(y_train,a,randw,0.15)

4
(135, 3)
3 done
(135, 5)
2 done
(135, 5)
1 done


In [94]:
layers = len(randw)+1
a[3].shape

(135, 3)

In [110]:
predict(X_test,bp)

array([[0.3844186 , 0.10770904, 0.16381188],
       [0.38383693, 0.10764607, 0.16401555],
       [0.38430744, 0.10844342, 0.16479228],
       [0.38427354, 0.10805226, 0.16441206],
       [0.38353977, 0.1078308 , 0.16433361],
       [0.38397417, 0.10747712, 0.16386343],
       [0.3841898 , 0.10792038, 0.16435042],
       [0.38387277, 0.10818179, 0.1644857 ],
       [0.38367251, 0.10764025, 0.16409877],
       [0.38409414, 0.10794714, 0.16418851],
       [0.38428718, 0.10831422, 0.16468567],
       [0.38438097, 0.10794201, 0.16425071],
       [0.38325722, 0.10832845, 0.16478205],
       [0.38414927, 0.10781051, 0.16424382],
       [0.38420416, 0.10754914, 0.16386166],
       [0.38407644, 0.10763004, 0.16393679],
       [0.38430551, 0.10835067, 0.16470213],
       [0.38422345, 0.10780878, 0.16422017],
       [0.38424279, 0.10806747, 0.1644533 ],
       [0.38424783, 0.10819462, 0.16457722],
       [0.38393864, 0.10764552, 0.16401664],
       [0.38325238, 0.10808349, 0.16460665],
       [0.